dependencies {
    // JWT
    compileOnly group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.5'
    runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-impl', version: '0.11.5'
    runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.11.5'

    testImplementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.5'
    testImplementation 'io.projectreactor:reactor-test'

    implementation 'org.springframework.cloud:spring-cloud-starter-gateway-server-webflux'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.projectlombok:lombok'
    implementation "org.springdoc:springdoc-openapi-starter-webflux-ui:${springdocVersion}"
    annotationProcessor 'org.projectlombok:lombok'
}
