CREATE DATABASE user_db;
CREATE DATABASE hub_db;
CREATE DATABASE company_db;
CREATE DATABASE order_db;
CREATE DATABASE delivery_db;
CREATE DATABASE ai_db;

\connect ai_db
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
