spring:
  application:
    name: company-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  # Flyway 설정 추가
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
