server:
  port: 8086

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ai_db}
  ai:
    model:
      chat: ${AI_CHAT_PROVIDER:none}
      embedding: ${AI_EMBEDDING_PROVIDER:none}
    google:
      genai:
        api-key: ${GEMINI_API_KEY:}
        chat:
          model: ${GEMINI_CHAT_MODEL:gemini-2.5-flash}
        embedding:
          text:
            options:
              model: ${GEMINI_EMBEDDING_MODEL:gemini-embedding-001}
    vectorstore:
      pgvector:
        initialize-schema: false
        index-type: HNSW
        distance-type: COSINE_DISTANCE
