server:
  port: 8082

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hub_db}
  cache:
    redis:
      time-to-live: 600000
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    hub-events: ${HUB_EVENTS_TOPIC:hub-events}

internal:
  hub-service:
    name: hub-service
    allowed-name: delivery-service
    key: ${HUB_INTERNAL_SERVICE_KEY}
