server:
  port: 8082

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hub_db}
  cache:
    redis:
      time-to-live: 600000

internal:
  service:
    name: hub-service
    allowed-name: delivery-service
    key: ${HUB_INTERNAL_SERVICE_KEY}
