server:
  port: 8084

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order_db}

internal:
  service:
    allowed-name: delivery-service
    name: order-service
    key: ${INTERNAL_SERVICE_KEY}
